# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import inscritos.models


class Migration(migrations.Migration):

    dependencies = [
        ('inscritos', '0003_auto_20170826_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrito',
            name='chave',
            field=models.CharField(default=inscritos.models.criar_chave, max_length=64, null=True, unique=True),
        ),
    ]
