# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 16:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artigos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artigo',
            name='categorias',
            field=models.ManyToManyField(related_name='artigos', to='artigos.Categoria'),
        ),
        migrations.AddField(
            model_name='artigo',
            name='etiquetas',
            field=models.ManyToManyField(related_name='artigos', to='artigos.Etiqueta'),
        ),
    ]
