# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 12:10
from __future__ import unicode_literals

import artigos.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0003_auto_20170812_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemArtigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('caminho', models.ImageField(upload_to=artigos.models.obter_caminho_da_imagem, verbose_name='Caminho')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='artigos.Artigo')),
            ],
            options={
                'verbose_name': 'Imagem de artigo',
                'verbose_name_plural': 'Imagens de artigo',
            },
        ),
    ]
