# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0004_imagemartigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, verbose_name='Slug'),
        ),
    ]
