# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 00:53
from __future__ import unicode_literals

from django.db import migrations
from django.utils import text


def slugify_título(apps, schema_editor):
    """Seta o valor de campos slug vazios em artigos anteriores a inclusão do campo slug."""
    Artigo = apps.get_model('artigos', 'Artigo')
    for artigo in Artigo.objects.all():
        artigo.slug = text.slugify(artigo.título)
        artigo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0005_artigo_slug'),
    ]

    operations = [
        migrations.RunPython(slugify_título)
    ]
