# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 00:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0006_auto_20170821_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug'),
        ),
    ]
